version: '3.1'

name: wp

services:
  mysql:
    image: mysql:latest
    restart: always
    environment:
      MYSQL_DATABASE: database
      MYSQL_USER: user
      MYSQL_PASSWORD: password
      MYSQL_RANDOM_ROOT_PASSWORD: '1'
    volumes:
      - ./mysql/:/var/lib/mysql

  adminer:
    image: adminer:latest
    restart: always
    depends_on:
      mysql:
        condition: service_started
    ports:
      - 9090:8080 

  wordpress:
    image: wordpress:latest
    restart: always
    depends_on: 
      mysql:
        condition: service_started
    ports:
      - 8080:80
    environment:
      WORDPRESS_DB_HOST: mysql
      WORDPRESS_DB_USER: user
      WORDPRESS_DB_PASSWORD: password
      WORDPRESS_DB_NAME: database
    volumes:
      - wordpress:/var/www/html
      - ./themes/:/var/www/html/wp-content/themes/
      - ./plugins/:/var/www/html/wp-content/plugins/
      - ./uploads/:/var/www/html/wp-content/uploads/

  wp-cli:
    container_name: wp-cli
    depends_on:
      wordpress:
        condition: service_started
      mysql:
        condition: service_started      
    image: wordpress:cli
    user: xfs
    volumes:
      - wordpress:/var/www/html
    environment:
      WORDPRESS_DB_HOST: mysql
      WORDPRESS_DB_USER: user
      WORDPRESS_DB_PASSWORD: password
      WORDPRESS_DB_NAME: database
    command: >
      /bin/sh -c '
        sleep 30;
        wp core install\
          --path="/var/www/html"\
          --url="http://localhost:8080"\
          --title="Local Wordpress By Docker"\
          --admin_user=user\
          --admin_password=password\
          --admin_email=foo@bar.com\
          --locale="ru_RU";

        wp core update\
          --locale="ru_RU";

        wp plugin install\
          woocommerce\
          create-block-theme\
          icon-block\
          media-sync\
          --activate;

        wp plugin update\
          --all;

      '

volumes:
  mysql:
  wordpress: