#!/bin/sh

git clone "https://github.com/Bezmie/bz-common.git" ./wordpress/wp-content/plugins/bz-common/

git clone "https://github.com/stanislavzadiraev/alpha.git" ./wordpress/wp-content/themes/alpha/
git clone "https://github.com/stanislavzadiraev/beta.git" ./wordpress/wp-content/themes/beta/