#!/bin/sh

git clone "https://github.com/Bezmie/bz-common.git" ./plugins/bz-common/

git clone "https://github.com/stanislavzadiraev/alpha.git" ./themes/alpha/
git clone "https://github.com/stanislavzadiraev/beta.git" ./themes/beta/